Feature/complete revision
relaycc/landing pull request #19
Opened 2022-08-17 17:15 UTC by BrianS111

2022-08-18 02:05 UTC, killthebuddh4 requested changes
TODO Items, in my opinion:

* The "About" link 404s
* hover states on mobile menu items
* hover states on mobile menu close button
* There's too much vertical space where elements were removed:
  * between the site navigation and the primary title
  * between the Relay, Receiver, Bridge, Prod buttons and the "Products" header
  * between the "Have some questions..." section and the page footer
* colors should be changed to match the Relay logo
* icons in the top-right corners of the product cards should be updated or deleted
* copy in the product cards needs to be updated
* images in the "learn more" and "questions" cards should be replaced
* every dead link should have a popup that says "This is coming soon..."
* One last thing I think we should do is to give some of the elements, in particular the cards, borders like the borders from this site https://ethglobal.com/showcase. I think we should also add those borders to the `profiles` components that are in Figma right now. That way, our landing page, profiles, and chat app will all look at least kind of the same.

2022-08-19 20:53 UTC, andrewvdp approved these changes

2022-08-19 23:14 UTC, killthebuddh4 requested changes
The only thing before merging is putting the asset files in `/public`.

2022-08-19 23:49 UTC, killthebuddh4 requested changes
* delete the /src/images/about/index.tsx file
* move all asset files into `/public`

2022-08-20 18:25 UTC, killthebuddh4 approved these changes

2022-08-20 18:27 UTC, merged